version: "3.7"
services:
  micro01:
    container_name: "micro01"
    image: jucmunozri/web:2
    ports:
      - "3001"
    networks:
      - micro-red
    environment:
      CONTAINER_HOST: "micro01"
  micro02:
    container_name: "micro02"
    image: jucmunozri/web:2
    ports:
      - "3001"
    networks:
      - micro-red
    environment:
      CONTAINER_HOST: "micro02"
  load-balancer-jucmunozri-v1:
    container_name: "load-balancer-jucmunozri-v1"
    image: load-balancer-jucmunozri-v1:v1
    build:
      context: ./load-balancer
    ports:
      - "6001:80"
    networks:
      - micro-red
    depends_on:
      - micro01
      - micro02
    restart: always
networks:
  micro-red:
